/**
 * AdNabbit Quick Start Script
 * Sets up your local .env file with the correct values
 */

const fs = require('fs');
const path = require('path');

const ENV_CONTENT = `# AdNabbit Local Development Environment
# Generated by quick-start.js

# Stripe Configuration (Test Mode)
STRIPE_SECRET_KEY=YOUR_STRIPE_SECRET_KEY_HERE
STRIPE_PUBLISHABLE_KEY=YOUR_STRIPE_PUBLISHABLE_KEY_HERE
STRIPE_WEBHOOK_SECRET=whsec_your_webhook_secret_here

# Stripe Price IDs (Your Actual Test Price IDs)
STRIPE_PRICE_BASIC=price_1RqnNGLmvO6Fl5tLfMBqACWI
STRIPE_PRICE_STANDARD=price_1RqnNeLmvO6Fl5tLoTcNTNe5
STRIPE_PRICE_PREMIUM=price_1RqnNtLmvO6Fl5tLeOcb6VK3

# Server Configuration
PORT=3001
NODE_ENV=development

# CORS Configuration
ALLOWED_ORIGINS=http://localhost:3000,https://adnabbit.com,https://www.adnabbit.com

# Logging
LOG_LEVEL=debug
`;

function createEnvFile() {
    const envPath = path.join(__dirname, '.env');
    
    if (fs.existsSync(envPath)) {
        console.log('⚠️  .env file already exists!');
        console.log('❓ Do you want to overwrite it? (y/N)');
        console.log('💡 You can manually update it or rename the existing one.');
        return;
    }
    
    try {
        fs.writeFileSync(envPath, ENV_CONTENT);
        console.log('✅ Created .env file with your Stripe configuration!');
        console.log('');
        console.log('🚀 Next steps:');
        console.log('1. npm install');
        console.log('2. npm run dev');
        console.log('3. Test payment flow on your website');
        console.log('');
        console.log('🔧 Optional: Set up webhook endpoint in Stripe Dashboard');
        console.log('   URL: http://localhost:3001/api/webhook (for local testing)');
        console.log('   URL: https://your-domain.com/api/webhook (for production)');
        
    } catch (error) {
        console.error('❌ Error creating .env file:', error.message);
    }
}

function checkDependencies() {
    const packagePath = path.join(__dirname, 'package.json');
    
    if (!fs.existsSync(packagePath)) {
        console.log('📦 Installing dependencies...');
        console.log('Run: npm install');
        return false;
    }
    
    const nodeModulesPath = path.join(__dirname, 'node_modules');
    if (!fs.existsSync(nodeModulesPath)) {
        console.log('📦 Dependencies not installed. Run: npm install');
        return false;
    }
    
    return true;
}

function main() {
    console.log('🚀 AdNabbit Stripe Quick Start\n');
    
    createEnvFile();
    
    if (checkDependencies()) {
        console.log('');
        console.log('🎉 Everything is ready!');
        console.log('Run: npm run dev');
    }
}

if (require.main === module) {
    main();
}

module.exports = { createEnvFile, checkDependencies };